### ISSUE TITLE
does NOT work with typescript

### ISSUE THREAD

**Issue by devdoomari** [pjeby/autocreate#2]
I think it's wrong to state that this library actually works with typescript.

there's no typescript definition file to be used with this library.

**Comment by pjeby** [comment]
I don't see how that's a requirement, since most JS libraries lack such definition files, and in any case the examples compile and run in the Typescript Playground site just fine.

**Comment by devdoomari** [comment]
> since most JS libraries lack such definition files

That's why most libraries don't state they support typescript.
Also, your examples may not compile fine for most projects with implicit-any forbidden.

**Comment by pjeby** [comment]
So, if I'm understanding this correctly, it sounds like you are _not_ saying that the library doesn't work, nor are you saying that you would _like_ a definition file, nor do you seem to be saying that you yourself _intend_ to use the library, but only if such a file exists.

So...  I'm unclear what the actual issue here is.  The only specific thing you've said is, "I think it's wrong to state that this library actually works with typescript."  But that statement is not actually *incorrect*, so I think we'll need to agree to disagree here.

Now, if what you're trying to say is that you found the documentation *misleading* as to the *availability of a definition file*, it might help if you provide a PR with either a documentation change (that clarifies the support is for Typescript *syntax*), or else adds the needed definition file(s).

(Or, failing a PR, at least provide a draft or sketch of what you would want to see as an additional disclaimer, so I have a better idea of what you're looking for.)

**Comment by devdoomari** [comment]
the only issue is that this library is advertised as "typescript-friendly" when it obviously isn't.

The description (& other relevant parts) of this project should change:
```
"new"-less classes for ES7/Babel, TypeScript, CoffeeScript, etc.
```
is plain misleading. (just remove "Typescript")

**Comment by pjeby** [comment]
I think I've already made clear the scope of change I'd accept, as well as what sort of arguments I'd be amenable to consider in extending that scope.  Since you're offering neither changes within that scope nor any arguments besides restating your original position, there's no point in continuing discussion.
